#include "print.h"
#include "main.h"     // for huart2
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

/* UART handle generated by CubeMX */
extern UART_HandleTypeDef huart2;

/* Binary semaphore to protect UART */
static osSemaphoreId_t uartPrintSem;

/**
 * @brief Initialize UART print semaphore
 */
void Print_Init(void)
{
    /* max count = 1, initial count = 1 (available) */
    uartPrintSem = osSemaphoreNew(1, 1, NULL);
}

/**
 * @brief Thread-safe UART print
 */
void Print_Line(const char *fmt, ...)
{
    char buffer[128];

    va_list args;
    va_start(args, fmt);
    vsnprintf(buffer, sizeof(buffer), fmt, args);
    va_end(args);

    /* Take UART semaphore */
    osSemaphoreAcquire(uartPrintSem, osWaitForever);

    HAL_UART_Transmit(&huart2,(uint8_t *)buffer,strlen(buffer),HAL_MAX_DELAY);

    /* newline */
    const char newline[] = "\r\n";
    HAL_UART_Transmit(&huart2,(uint8_t *)newline,sizeof(newline) - 1,HAL_MAX_DELAY);

    /* Release UART semaphore */
    osSemaphoreRelease(uartPrintSem);
}
